import java.sql.*;
import java.util.List;

import domain.*;
import repositories.IRepository;
import repositories.IRepositoryCatalog;
import impl.DummyRepositoryCatalog;
import impl.RepositoryCatalog;
import impl.StudentBuilder;
import impl.StudentRepository;
import unitofwork.IUnitOfWork;
import unitofwork.UnitOfWork;


public class Main {

		
		public static void main(String[] args) {

			String url="jdbc:hsqldb:hsql://localhost/";
			Student MDlugi = new Student();
			MDlugi.setIndex("s12116");
			
			try {
				
				Connection connection = DriverManager.getConnection(url);
				IUnitOfWork uow = new UnitOfWork(connection);
				
				
				String createTableSql =
				"CREATE TABLE students("
				+ "id int GENERATED BY DEFAULT AS IDENTITY,"
				+ "index VARCHAR(20),"
				+ ")";
				Statement createTable = connection.createStatement();
				createTable.executeUpdate(createTableSql);
				
				IRepositoryCatalog catalog = new RepositoryCatalog(connection, uow);
				
				catalog.getStudents().save(MDlugi);
				
				List<Student> studentsFromDb= catalog.getStudents().getAll();
				
				for(Student studentFromDb: studentsFromDb)
					System.out.println(studentFromDb.getId()+" "+studentFromDb.getIndex());
				
				
				
				
				} catch (SQLException e) {
					e.printStackTrace();
			}
			System.out.println("koniec");
		}
}

